# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-MulanPubL-2.0-or-later
# SPDX-FileCopyrightText: 2026 AdwCode contributors
[environment]
python-version = "3.9"
extra-paths = ["源码"]

[src]
include = ["源码", "测试", "基准"]

[rules]
all = "error"
