# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 AdwCode contributors
"""VS Code 工作台颜色到 Adwaita 角色的映射。

映射遵循 libadwaita 1.10 的约定：

- 窗口 / 标题栏 / 侧栏 / 视图各表面保留各自色阶；
- 列表选中使用 25% 强调色（对应 ``--view-selected-color``）；
- 悬停与“激活”背景分别为前景色的 7% / 12%；
- 边框为 ``currentColor`` 的 15%（高对比度为 50%）；
- 标签页对齐 ``AdwTabBar``：中性色条带、活动标签 10% 高亮。
"""

from __future__ import annotations

from typing import Literal

from palette import ANSI, PALETTE, Palette, rgba
from tokens import load_scheme


def build_ui_colors(p: Palette, colorful_status_bar: bool = False) -> dict[str, str]:
    dark = p.mode == "dark"
    styles = load_scheme(p.mode)["styles"]

    def sy(
        name: str,
        key: Literal["foreground", "background"] = "foreground",
        fallback: str | None = None,
    ) -> str | None:
        info = styles.get(name)
        return (info[key] if info is not None else None) or fallback

    def hue(name: str, level_dark: int = 2, level_light: int = 4) -> str:
        return PALETTE[name][level_dark if dark else level_light]

    colors: dict[str, str | None] = {
        # --- 全局 ---
        "foreground": p["fg"],
        "disabledForeground": p["fg_disabled"],
        "errorForeground": p["error_standalone"],
        "descriptionForeground": p["fg_dim"],
        "icon.foreground": p["fg_dim"],
        "focusBorder": rgba(p["accent_bg"], 0.75),
        # contrastBorder/contrastActiveBorder 仅属于高对比度主题：VS Code 的 CSS
        # 以 `unset`/`transparent` 作为回退，普通主题里定义它们会到处多出描边。
        "contrastBorder": p["contrast_border"] if p.high_contrast else None,
        "contrastActiveBorder": rgba(p["accent_bg"], 0.75) if p.high_contrast else None,
        "widget.shadow": "#00000066" if dark else "#00000026",
        "widget.border": "#00000000",
        "selection.background": rgba(p["accent_bg"], 0.35),
        "sash.hoverBorder": rgba(p["accent_bg"], 0.75),
        "badge.background": p["accent_bg"],
        "badge.foreground": p["accent_fg"],
        "progressBar.background": p["accent_bg"],
        "textLink.foreground": p["accent_standalone"],
        "textLink.activeForeground": p["accent_hover"],
        "textPreformat.foreground": hue("teal", 4, 5),
        "textBlockQuote.background": p["bg_hover_view"],
        "textBlockQuote.border": p["border"],
        "textCodeBlock.background": p["bg_hover_view"],
        "textSeparator.foreground": p["border_dim"],
        "keybindingLabel.background": p["bg_card"],
        "keybindingLabel.foreground": p["fg_card"],
        "keybindingLabel.border": p["border"],
        "keybindingLabel.bottomBorder": p["border_dim"],
        "keybindingTable.headerBackground": p["bg_headerbar"],
        "keybindingTable.rowsBackground": p["bg_window"],
        "banner.background": p["warning_bg"],
        "banner.foreground": p["warning_fg"],
        "banner.iconForeground": p["warning_fg"],
        # --- 窗口 / 标题栏 ---
        "window.activeBorder": "#00000000",
        "window.inactiveBorder": "#00000000",
        "titleBar.activeBackground": p["bg_headerbar"],
        "titleBar.activeForeground": p["fg_headerbar"],
        "titleBar.inactiveBackground": p["bg_headerbar_backdrop"],
        "titleBar.inactiveForeground": p["fg_dim_headerbar"],
        "titleBar.border": "#00000000",
        # --- 活动栏 ---
        "activityBar.background": p["bg_sidebar"],
        "activityBar.foreground": p["fg_sidebar"],
        "activityBar.inactiveForeground": p["fg_dim_sidebar"],
        "activityBar.border": p["sidebar_border"] if p.high_contrast else "#00000000",
        "activityBar.activeBackground": p["bg_active_sidebar"],
        "activityBar.activeBorder": "#00000000",
        "activityBar.activeFocusBorder": rgba(p["accent_bg"], 0.75),
        "activityBar.dropBorder": rgba(p["accent_bg"], 0.75),
        "activityBarTop.background": p["bg_sidebar"],
        "activityBarTop.foreground": p["fg_sidebar"],
        "activityBarTop.inactiveForeground": p["fg_dim_sidebar"],
        "activityBarTop.activeBorder": "#00000000",
        "activityBarTop.activeBackground": p["bg_active_sidebar"],
        "activityBarTop.dropBorder": rgba(p["accent_bg"], 0.75),
        "activityBarBadge.background": p["accent_bg"],
        "activityBarBadge.foreground": p["accent_fg"],
        "activityErrorBadge.background": p["error_bg"],
        "activityErrorBadge.foreground": p["error_fg"],
        "activityWarningBadge.background": p["warning_bg"],
        "activityWarningBadge.foreground": p["warning_fg"],
        # --- 侧栏 ---
        "sideBar.background": p["bg_sidebar"],
        "sideBar.foreground": p["fg_sidebar"],
        "sideBar.border": p["sidebar_border"],
        "sideBar.dropBackground": rgba(p["accent_bg"], 0.12),
        "sideBarTitle.foreground": p["fg_sidebar"],
        "sideBarSectionHeader.background": "#00000000",
        "sideBarSectionHeader.foreground": p["fg_dim_sidebar"],
        "sideBarSectionHeader.border": p["border_dim"],
        "sideBarActivityBarTop.border": "#00000000",
        # --- 状态栏 ---
        "statusBar.background": p["bg_headerbar"],
        "statusBar.foreground": p["fg_headerbar"],
        "statusBar.border": "#00000000",
        "statusBar.debuggingBackground": p["warning_bg"],
        "statusBar.debuggingForeground": p["warning_fg"],
        "statusBar.debuggingBorder": "#00000000",
        "statusBar.noFolderBackground": p["bg_headerbar"],
        "statusBar.noFolderForeground": p["fg_headerbar"],
        "statusBar.noFolderBorder": "#00000000",
        "statusBarItem.hoverBackground": p["bg_hover_headerbar"],
        "statusBarItem.hoverForeground": p["fg_headerbar"],
        "statusBarItem.activeBackground": p["bg_active_headerbar"],
        "statusBarItem.prominentBackground": p["bg_active_headerbar"],
        "statusBarItem.prominentForeground": p["fg_headerbar"],
        "statusBarItem.prominentHoverBackground": p["bg_active_headerbar"],
        "statusBarItem.remoteBackground": p["accent_bg"],
        "statusBarItem.remoteForeground": p["accent_fg"],
        "statusBarItem.remoteHoverBackground": p["accent_hover"],
        "statusBarItem.remoteHoverForeground": p["accent_fg"],
        "statusBarItem.errorBackground": p["error_bg"],
        "statusBarItem.errorForeground": p["error_fg"],
        "statusBarItem.errorHoverBackground": p["destructive_standalone"],
        "statusBarItem.errorHoverForeground": p["error_fg"],
        "statusBarItem.warningBackground": p["warning_bg"],
        "statusBarItem.warningForeground": p["warning_fg"],
        "statusBarItem.warningHoverBackground": p["warning_standalone"],
        "statusBarItem.warningHoverForeground": p["warning_fg"],
        "statusBarItem.offlineBackground": p["destructive_bg"],
        "statusBarItem.offlineForeground": p["destructive_fg"],
        "statusBarItem.offlineHoverBackground": p["destructive_standalone"],
        "statusBarItem.offlineHoverForeground": p["destructive_fg"],
        # --- 编辑器 ---
        "editor.background": p["editor_bg"],
        "editor.foreground": p["editor_fg"],
        "editorPane.background": p["editor_bg"],
        "editorCursor.foreground": p["editor_cursor"],
        "editorCursor.background": p["editor_bg"],
        "editorLineNumber.foreground": p["editor_line_number"],
        "editorLineNumber.activeForeground": p["editor_fg"],
        "editorLineNumber.dimmedForeground": p["fg_disabled_view"],
        "editor.lineHighlightBackground": p["editor_line_highlight"],
        "editor.lineHighlightBorder": "#00000000",
        "editor.selectionBackground": p["selection"],
        "editor.inactiveSelectionBackground": p["selection_inactive"],
        "editor.selectionHighlightBackground": p["selection_highlight"],
        "editor.selectionHighlightBorder": "#00000000",
        "editor.wordHighlightBackground": p["word_highlight"],
        "editor.wordHighlightStrongBackground": p["word_highlight_strong"],
        "editor.wordHighlightTextBackground": p["word_highlight_strong"],
        "editor.findMatchBackground": p["find_match"],
        "editor.findMatchForeground": p["editor_search_match_fg"],
        "editor.findMatchHighlightBackground": p["find_match_highlight"],
        "editor.findRangeHighlightBackground": p["selection_highlight"],
        "editor.hoverHighlightBackground": p["bg_hover_view"],
        "editor.rangeHighlightBackground": p["bg_hover_view"],
        "editor.rangeHighlightBorder": "#00000000",
        "editorWhitespace.foreground": p["editor_ruler"],
        "editorIndentGuide.background": p["indent_guide"],
        "editorIndentGuide.background1": p["indent_guide"],
        "editorIndentGuide.activeBackground": p["indent_guide_active"],
        "editorIndentGuide.activeBackground1": p["indent_guide_active"],
        "editorRuler.foreground": p["editor_ruler"],
        "editorBracketMatch.background": p["bracket_match"],
        "editorBracketMatch.border": p["bracket_border"],
        "editorBracketHighlight.foreground1": hue("blue", 2, 4),
        "editorBracketHighlight.foreground2": hue("orange", 2, 4),
        "editorBracketHighlight.foreground3": hue("purple", 1, 4),
        "editorBracketHighlight.foreground4": hue("green", 2, 5),
        "editorBracketHighlight.foreground5": hue("pink", 2, 5),
        "editorBracketHighlight.foreground6": hue("teal", 2, 5),
        "editorBracketHighlight.unexpectedBracket.foreground": p["error_standalone"],
        "editorLink.activeForeground": p["accent_standalone"],
        "editorPlaceholder.foreground": p["fg_placeholder"],
        "editorGhostText.foreground": p["fg_disabled_view"],
        "editorGhostText.background": "#00000000",
        "editorCodeLens.foreground": p["fg_dim_view"],
        "editorLightBulb.foreground": p["warning_standalone"],
        "editorLightBulbAutoFix.foreground": p["accent_standalone"],
        "editorLightBulbAi.foreground": p["accent_standalone"],
        "editorError.foreground": p["error_standalone"],
        "editorError.background": rgba(p["error_bg"], 0.12),
        "editorWarning.foreground": p["warning_standalone"],
        "editorWarning.background": rgba(p["warning_bg"], 0.12),
        "editorInfo.foreground": p["accent_standalone"],
        "editorInfo.background": rgba(p["accent_bg"], 0.12),
        "editorHint.foreground": p["success_standalone"],
        "editorHint.border": p["success_bg"],
        "editorUnnecessaryCode.border": p["border"],
        "editorInlayHint.foreground": p["fg_dim_view"],
        "editorInlayHint.background": p["bg_hover_view"],
        "editorInlayHint.typeForeground": p["fg_dim_view"],
        "editorInlayHint.typeBackground": p["bg_hover_view"],
        "editorInlayHint.parameterForeground": p["fg_dim_view"],
        "editorInlayHint.parameterBackground": p["bg_hover_view"],
        "editorUnicodeHighlight.border": p["warning_standalone"],
        "editorUnicodeHighlight.background": "#00000000",
        "editorCommentsWidget.rangeBackground": rgba(p["accent_bg"], 0.12),
        "editorCommentsWidget.rangeActiveBackground": rgba(p["accent_bg"], 0.2),
        "editorCommentsWidget.replyInputBackground": p["bg_input"],
        "editorCommentsWidget.resolvedBorder": p["success_standalone"],
        "editorCommentsWidget.unresolvedBorder": p["accent_standalone"],
        # 装订线（gutter）
        "editorGutter.background": p["editor_bg"],
        "editorGutter.addedBackground": p["success_standalone"],
        "editorGutter.modifiedBackground": p["accent_standalone"],
        "editorGutter.deletedBackground": p["error_standalone"],
        "editorGutter.foldingControlForeground": p["fg_dim_view"],
        "editorGutter.commentRangeForeground": p["fg_disabled_view"],
        "editorGutter.addedSecondaryBackground": p["success_bg"],
        "editorGutter.modifiedSecondaryBackground": p["accent_bg"],
        "editorGutter.deletedSecondaryBackground": p["error_bg"],
        # 概览标尺
        "editorOverviewRuler.border": "#00000000",
        "editorOverviewRuler.addedForeground": p["success_standalone"],
        "editorOverviewRuler.deletedForeground": p["error_standalone"],
        "editorOverviewRuler.modifiedForeground": p["accent_standalone"],
        "editorOverviewRuler.errorForeground": p["error_standalone"],
        "editorOverviewRuler.warningForeground": p["warning_standalone"],
        "editorOverviewRuler.infoForeground": p["accent_standalone"],
        "editorOverviewRuler.findMatchForeground": p["find_match"],
        "editorOverviewRuler.bracketMatchForeground": p["bracket_border"],
        "editorOverviewRuler.selectionHighlightForeground": p["selection_highlight"],
        "editorOverviewRuler.wordHighlightForeground": p["word_highlight"],
        "editorOverviewRuler.wordHighlightStrongForeground": p["word_highlight_strong"],
        # --- 编辑器组 / 标签页 ---
        "editorGroup.border": p["border"],
        "editorGroup.dropBackground": rgba(p["accent_bg"], 0.12),
        "editorGroup.dropIntoPromptForeground": p["fg_dim"],
        "editorGroup.dropIntoPromptBackground": p["bg_popover"],
        "editorGroup.emptyBackground": p["bg_window"],
        "editorGroup.focusedEmptyBorder": "#00000000",
        "editorGroupHeader.tabsBackground": p["bg_headerbar"],
        "editorGroupHeader.tabsBorder": "#00000000",
        "editorGroupHeader.border": "#00000000",
        "editorGroupHeader.noTabsBackground": p["bg_window"],
        "editorGroupHeader.connectedTabsBackground": p["bg_headerbar"],
        "tab.activeBackground": p.over(p["fg"], 0.10, "bg_headerbar"),
        "tab.activeForeground": p["fg_headerbar"],
        "tab.activeBorder": "#00000000",
        "tab.activeBorderTop": "#00000000",
        "tab.activeModifiedBorder": p["accent_bg"],
        "tab.unfocusedActiveBackground": p.over(p["fg"], 0.06, "bg_headerbar_backdrop"),
        "tab.unfocusedActiveForeground": p["fg_dim_headerbar"],
        "tab.unfocusedActiveBorder": "#00000000",
        "tab.unfocusedActiveBorderTop": "#00000000",
        "tab.unfocusedActiveModifiedBorder": p["border_dim"],
        "tab.inactiveBackground": p["bg_headerbar"],
        "tab.inactiveForeground": p["fg_dim_headerbar"],
        "tab.inactiveModifiedBorder": p["border_dim"],
        "tab.unfocusedInactiveBackground": p["bg_headerbar_backdrop"],
        "tab.unfocusedInactiveForeground": p["fg_disabled_headerbar"],
        "tab.hoverBackground": p["bg_hover_headerbar"],
        "tab.hoverForeground": p["fg_headerbar"],
        "tab.hoverBorder": "#00000000",
        "tab.unfocusedHoverBackground": p["bg_hover_headerbar"],
        "tab.unfocusedHoverForeground": p["fg_headerbar"],
        "tab.unfocusedHoverBorder": "#00000000",
        "tab.border": "#00000000",
        "tab.lastPinnedBorder": p["border_dim"],
        "tab.selectedBorderTop": "#00000000",
        "tab.selectedBackground": p.over(p["fg"], 0.10, "bg_headerbar"),
        "tab.selectedForeground": p["fg_headerbar"],
        "tab.dragAndDropBorder": rgba(p["accent_bg"], 0.75),
        # --- 面包屑 ---
        "breadcrumb.background": p["editor_bg"],
        "breadcrumb.foreground": p["fg_dim_view"],
        "breadcrumb.focusForeground": p["fg_view"],
        "breadcrumb.activeSelectionForeground": p["fg_view"],
        "breadcrumbPicker.background": p["bg_popover"],
        # --- 浮层组件 ---
        "editorWidget.background": p["bg_popover"],
        "editorWidget.foreground": p["fg_popover"],
        "editorWidget.border": p["border"],
        "editorWidget.resizeBorder": p["accent_bg"],
        "editorWidget.shadow": "#00000066" if dark else "#00000026",
        "editorWidget.prominentForeground": p["fg_popover"],
        "editorWidget.prominentBorder": p["border"],
        "editorWidget.prominentBackground": p["bg_hover_popover"],
        "editorWidget.errorBorder": p["error_bg"],
        "editorWidget.warningBorder": p["warning_bg"],
        "editorWidget.infoBorder": p["accent_bg"],
        "editorHoverWidget.background": p["bg_popover"],
        "editorHoverWidget.foreground": p["fg_popover"],
        "editorHoverWidget.border": p["border"],
        "editorHoverWidget.statusBarBackground": p["bg_headerbar"],
        "editorHoverWidget.highlightForeground": p["accent_standalone"],
        "editorSuggestWidget.background": p["bg_popover"],
        "editorSuggestWidget.border": p["border"],
        "editorSuggestWidget.foreground": p["fg_popover"],
        "editorSuggestWidget.focusHighlightForeground": p["accent_standalone"],
        "editorSuggestWidget.highlightForeground": p["accent_standalone"],
        "editorSuggestWidget.selectedBackground": p.over(p["accent_bg"], 0.25, "bg_popover"),
        "editorSuggestWidget.selectedForeground": p["fg_popover"],
        "editorSuggestWidget.selectedIconForeground": p["accent_standalone"],
        "editorSuggestWidgetStatus.foreground": p["fg_dim_popover"],
        "editorMarkerNavigation.background": p["bg_popover"],
        "editorMarkerNavigationError.background": p["error_bg"],
        "editorMarkerNavigationWarning.background": p["warning_bg"],
        "editorMarkerNavigationInfo.background": p["accent_bg"],
        "editorStickyScroll.background": p["bg_card"],
        "editorStickyScroll.border": p["border"],
        "editorStickyScroll.shadow": "#000000ff",
        "editorStickyScrollHover.background": p["bg_hover_card"],
        "inlineChat.background": p["bg_popover"],
        "inlineChat.foreground": p["fg_popover"],
        "inlineChat.border": p["border"],
        "inlineChat.shadow": "#00000066" if dark else "#00000026",
        "inlineChatInput.background": p["bg_input"],
        "inlineChatInput.border": p["border_input"],
        "inlineChatInput.focusBorder": rgba(p["accent_bg"], 0.75),
        "inlineChatInput.placeholderForeground": p["fg_placeholder"],
        "inlineChatDiff.inserted": rgba(p["success_bg"], 0.2),
        "inlineChatDiff.removed": rgba(p["error_bg"], 0.2),
        # --- 列表 / 菜单 ---
        "list.activeSelectionBackground": p.over(p["accent_bg"], 0.25, "bg_sidebar"),
        "list.activeSelectionForeground": p["fg_sidebar"],
        "list.activeSelectionIconForeground": p["fg_sidebar"],
        "list.inactiveSelectionBackground": p["bg_active_sidebar"],
        "list.inactiveSelectionForeground": p["fg_sidebar"],
        "list.inactiveSelectionIconForeground": p["fg_dim_sidebar"],
        "list.focusBackground": p.over(p["accent_bg"], 0.25, "bg_sidebar"),
        "list.focusForeground": p["fg_sidebar"],
        "list.focusOutline": rgba(p["accent_bg"], 0.75),
        "list.focusAndSelectionOutline": rgba(p["accent_bg"], 0.75),
        "list.hoverBackground": p["bg_hover_sidebar"],
        "list.hoverForeground": p["fg_sidebar"],
        "list.highlightForeground": p["accent_standalone"],
        "list.focusHighlightForeground": p["accent_standalone"],
        "list.dropBackground": rgba(p["accent_bg"], 0.12),
        "list.errorForeground": p["error_standalone"],
        "list.warningForeground": p["warning_standalone"],
        "list.deemphasizedForeground": p["fg_disabled_sidebar"],
        "listFilterWidget.background": p["bg_popover"],
        "listFilterWidget.outline": "#00000000",
        "listFilterWidget.noMatchesOutline": p["error_bg"],
        "listFilterWidget.shadow": "#00000066" if dark else "#00000026",
        "tree.indentGuidesStroke": p["indent_guide"],
        "tree.inactiveIndentGuidesStroke": p["border_dim"],
        "tree.tableColumnsBorder": p["border_dim"],
        "tree.tableOddRowsBackground": "#00000000",
        "menu.background": p["bg_popover"],
        "menu.foreground": p["fg_popover"],
        "menu.border": p["border"],
        "menu.selectionBackground": p.over(p["fg_popover"], 0.10, "bg_popover"),
        "menu.selectionForeground": p["fg_popover"],
        "menu.selectionBorder": "#00000000",
        "menu.separatorBackground": p["border_dim"],
        "menubar.selectionBackground": p["bg_hover_popover"],
        "menubar.selectionForeground": p["fg_popover"],
        "menubar.selectionBorder": "#00000000",
        # --- 输入控件 ---
        "input.background": p["bg_input"],
        "input.foreground": p["fg_view"],
        "input.border": p["border_input"],
        "input.placeholderForeground": p["fg_placeholder"],
        "inputOption.activeBackground": p["accent_bg"],
        "inputOption.activeForeground": p["accent_fg"],
        "inputOption.activeBorder": p["accent_bg"],
        "inputOption.hoverBackground": p["bg_hover_view"],
        "inputValidation.errorBackground": p.over(p["error_bg"], 0.15, "bg_input"),
        "inputValidation.errorForeground": p["error_standalone"],
        "inputValidation.errorBorder": p["error_bg"],
        "inputValidation.warningBackground": p.over(p["warning_bg"], 0.15, "bg_input"),
        "inputValidation.warningForeground": p["warning_standalone"],
        "inputValidation.warningBorder": p["warning_bg"],
        "inputValidation.infoBackground": p.over(p["accent_bg"], 0.15, "bg_input"),
        "inputValidation.infoForeground": p["accent_standalone"],
        "inputValidation.infoBorder": p["accent_bg"],
        "dropdown.background": p["bg_popover"],
        "dropdown.foreground": p["fg_popover"],
        "dropdown.border": p["border_input"],
        "dropdown.listBackground": p["bg_popover"],
        "checkbox.background": p["bg_input"],
        "checkbox.foreground": p["fg_view"],
        "checkbox.border": p["border_input"],
        "checkbox.selectBackground": p["bg_active_view"],
        "checkbox.selectBorder": rgba(p["accent_bg"], 0.75),
        "radio.activeForeground": p["accent_standalone"],
        "radio.inactiveForeground": p["fg_dim_view"],
        "radio.activeBackground": "#00000000",
        "radio.inactiveBackground": "#00000000",
        "radio.activeBorder": p["accent_bg"],
        "radio.inactiveBorder": p["border_input"],
        "radio.inactiveHoverBackground": "#00000000",
        # --- 按钮 ---
        "button.background": p["accent_bg"],
        "button.foreground": p["accent_fg"],
        "button.border": p["accent_bg"],
        "button.hoverBackground": p["accent_hover"],
        "button.separator": "#00000000",
        "button.secondaryBackground": p["bg_button"],
        "button.secondaryForeground": p["fg"],
        "button.secondaryBorder": p["bg_button"],
        "button.secondaryHoverBackground": p["bg_button_hover"],
        "extensionButton.background": p["accent_bg"],
        "extensionButton.foreground": p["accent_fg"],
        "extensionButton.hoverBackground": p["accent_hover"],
        "extensionButton.border": p["accent_bg"],
        "extensionButton.separator": "#00000000",
        "extensionButton.prominentBackground": p["accent_bg"],
        "extensionButton.prominentForeground": p["accent_fg"],
        "extensionButton.prominentHoverBackground": p["accent_hover"],
        "extensionButton.prominentBorder": p["accent_bg"],
        "extensionBadge.remoteBackground": p["accent_bg"],
        "extensionBadge.remoteForeground": p["accent_fg"],
        "profileBadge.background": p["accent_bg"],
        "profileBadge.foreground": p["accent_fg"],
        # --- 快速输入 ---
        "quickInput.background": p["bg_popover"],
        "quickInput.foreground": p["fg_popover"],
        "quickInputTitle.background": p["bg_headerbar"],
        "quickInputList.focusBackground": p.over(p["accent_bg"], 0.25, "bg_popover"),
        "quickInputList.focusForeground": p["fg_popover"],
        "quickInputList.focusIconForeground": p["accent_standalone"],
        "pickerGroup.foreground": p["fg_dim_popover"],
        "pickerGroup.border": p["border_dim"],
        # --- 面板 / 输出 / 终端 ---
        "panel.background": p["bg_window"],
        "panel.border": p["border"] if p.high_contrast else p["border_dim"],
        "panel.dropBorder": rgba(p["accent_bg"], 0.75),
        "panelTitle.activeForeground": p["fg_window"],
        "panelTitle.activeBorder": p["accent_bg"],
        "panelTitle.inactiveForeground": p["fg_dim_window"],
        "panelTitle.border": "#00000000",
        "panelSection.border": p["border_dim"],
        "panelSection.dropBackground": rgba(p["accent_bg"], 0.12),
        "panelSectionHeader.background": p["bg_window"],
        "panelSectionHeader.foreground": p["fg_dim_window"],
        "panelSectionHeader.border": p["border_dim"],
        "panelStickyScroll.background": p["bg_card"],
        "panelStickyScroll.border": p["border"],
        "terminal.background": p["bg_view"],
        "terminal.foreground": p["editor_fg"],
        "terminal.border": p["border_dim"],
        "terminal.selectionBackground": p["selection"],
        "terminal.inactiveSelectionBackground": p["selection_inactive"],
        "terminal.selectionForeground": p["editor_fg"],
        "terminalCursor.foreground": p["accent_standalone"],
        "terminalCursor.background": p["bg_view"],
        "terminal.findMatchBackground": p["find_match"],
        "terminal.findMatchHighlightBackground": p["find_match_highlight"],
        "terminal.hoverHighlightBackground": p["bg_hover_view"],
        "terminal.dropBackground": rgba(p["accent_bg"], 0.12),
        "terminal.tab.activeBorder": p["accent_bg"],
        "terminalCommandDecoration.defaultBackground": p["fg_dim_view"],
        "terminalCommandDecoration.successBackground": p["success_standalone"],
        "terminalCommandDecoration.errorBackground": p["error_standalone"],
        "ports.iconRunningProcessForeground": p["success_standalone"],
        **ANSI,
        # --- 问题 / 调试 ---
        "problemsErrorIcon.foreground": p["error_standalone"],
        "problemsWarningIcon.foreground": p["warning_standalone"],
        "problemsInfoIcon.foreground": p["accent_standalone"],
        "debugToolBar.background": p["bg_headerbar"],
        "debugToolBar.border": "#00000000",
        "debugConsole.errorForeground": p["error_standalone"],
        "debugConsole.infoForeground": p["accent_standalone"],
        "debugConsole.warningForeground": p["warning_standalone"],
        "debugConsole.sourceForeground": p["fg_dim"],
        "debugConsoleInputIcon.foreground": p["accent_standalone"],
        "debugExceptionWidget.background": p["bg_popover"],
        "debugExceptionWidget.border": p["error_bg"],
        "debugIcon.breakpointForeground": p["error_standalone"],
        "debugIcon.breakpointDisabledForeground": p["fg_disabled"],
        "debugIcon.breakpointUnverifiedForeground": p["fg_dim"],
        "debugIcon.breakpointCurrentStackframeForeground": p["warning_standalone"],
        "debugIcon.breakpointStackframeForeground": p["success_standalone"],
        "debugIcon.startForeground": p["success_standalone"],
        "debugIcon.pauseForeground": p["accent_standalone"],
        "debugIcon.stopForeground": p["error_standalone"],
        "debugIcon.disconnectForeground": p["error_standalone"],
        "debugIcon.restartForeground": p["success_standalone"],
        "debugIcon.stepOverForeground": p["accent_standalone"],
        "debugIcon.stepIntoForeground": p["accent_standalone"],
        "debugIcon.stepOutForeground": p["accent_standalone"],
        "debugIcon.continueForeground": p["accent_standalone"],
        "debugTokenExpression.name": sy("def:identifier", fallback=p["fg"]),
        "debugTokenExpression.value": sy("def:string", fallback=p["fg"]),
        "debugTokenExpression.string": sy("def:string", fallback=p["fg"]),
        "debugTokenExpression.boolean": sy("def:boolean", fallback=p["fg"]),
        "debugTokenExpression.number": sy("def:number", fallback=p["fg"]),
        "debugTokenExpression.error": p["error_standalone"],
        "debugView.exceptionLabelBackground": p["error_bg"],
        "debugView.exceptionLabelForeground": p["error_fg"],
        "debugView.stateLabelBackground": p["accent_bg"],
        "debugView.stateLabelForeground": p["accent_fg"],
        "debugView.valueChangedHighlight": p["accent_bg"],
        # --- Git / 源代码管理 ---
        "gitDecoration.addedResourceForeground": p["success_standalone"],
        "gitDecoration.untrackedResourceForeground": p["success_standalone"],
        "gitDecoration.renamedResourceForeground": p["success_standalone"],
        "gitDecoration.modifiedResourceForeground": p["warning_standalone"],
        "gitDecoration.stageModifiedResourceForeground": p["warning_standalone"],
        "gitDecoration.deletedResourceForeground": p["error_standalone"],
        "gitDecoration.stageDeletedResourceForeground": p["error_standalone"],
        "gitDecoration.conflictingResourceForeground": p["error_standalone"],
        "gitDecoration.submoduleResourceForeground": hue("purple", 1, 4),
        "gitDecoration.ignoredResourceForeground": p["fg_disabled_sidebar"],
        "scm.providerBorder": p["border_dim"],
        "git.blame.editorDecorationForeground": p["fg_dim_view"],
        # --- 差异 / 合并 ---
        "diffEditor.insertedTextBackground": p["diff_inserted"],
        "diffEditor.removedTextBackground": p["diff_removed"],
        "diffEditor.insertedLineBackground": p["diff_inserted_bg"],
        "diffEditor.removedLineBackground": p["diff_removed_bg"],
        "diffEditor.diagonalFill": p["bg_hover_view"],
        "diffEditor.unchangedRegionBackground": p["bg_window"],
        "diffEditor.unchangedRegionForeground": p["fg_dim_window"],
        "diffEditor.unchangedRegionShadow": "#00000000",
        "diffEditor.unchangedCodeBackground": "#00000000",
        "diffEditor.border": p["border"],
        "diffEditorGutter.insertedLineBackground": p["diff_inserted_bg"],
        "diffEditorGutter.removedLineBackground": p["diff_removed_bg"],
        "diffEditorOverview.insertedForeground": p["success_standalone"],
        "diffEditorOverview.removedForeground": p["error_standalone"],
        "multiDiffEditor.background": p["editor_bg"],
        "multiDiffEditor.border": p["border"],
        "multiDiffEditor.headerBackground": p["bg_headerbar"],
        "mergeEditor.change.background": rgba(p["success_bg"], 0.25),
        "mergeEditor.change.word.background": rgba(p["success_bg"], 0.4),
        "mergeEditor.changeBase.background": rgba(p["fg_dim"], 0.25),
        "mergeEditor.changeBase.word.background": rgba(p["fg_dim"], 0.4),
        "mergeEditor.conflict.unhandledFocused.border": p["accent_bg"],
        "mergeEditor.conflict.unhandledUnfocused.border": p["border"],
        "mergeEditor.conflict.handledFocused.border": p["border"],
        "mergeEditor.conflict.handledUnfocused.border": p["border_dim"],
        "mergeEditor.conflict.handled.minimapOverViewRuler": p["success_standalone"],
        "mergeEditor.conflict.unhandled.minimapOverViewRuler": p["warning_standalone"],
        "mergeEditor.conflict.input1.background": rgba(p["accent_bg"], 0.2),
        "mergeEditor.conflict.input2.background": rgba(p["accent_bg"], 0.2),
        # --- Notebook ---
        "notebook.editorBackground": p["editor_bg"],
        "notebook.cellBorderColor": p["border"],
        "notebook.cellHoverBackground": p["bg_hover_view"],
        "notebook.cellInsertionIndicator": p["accent_bg"],
        "notebook.cellStatusBarItemHoverBackground": p["bg_hover_view"],
        "notebook.cellToolbarSeparator": p["border_dim"],
        "notebook.selectedCellBackground": rgba(p["accent_bg"], 0.12),
        "notebook.selectedCellBorder": p["accent_bg"],
        "notebook.inactiveSelectedCellBorder": p["border_input"],
        "notebook.focusedCellBorder": p["accent_bg"],
        "notebook.focusedEditorBorder": p["accent_bg"],
        "notebook.outputContainerBackgroundColor": p["bg_window"],
        "notebook.outputContainerBorderColor": "#00000000",
        # --- 测试 ---
        "testing.iconFailed": p["error_standalone"],
        "testing.iconErrored": p["error_standalone"],
        "testing.iconPassed": p["success_standalone"],
        "testing.iconQueued": p["fg_dim"],
        "testing.iconUnset": p["fg_disabled"],
        "testing.iconSkipped": p["fg_disabled"],
        "testing.runAction": p["success_standalone"],
        "testing.peekBorder": p["border"],
        "testing.peekHeaderBackground": p["bg_headerbar"],
        "testing.message.error.lineBackground": rgba(p["error_bg"], 0.12),
        "testing.message.info.decorationForeground": p["fg_dim_view"],
        "testing.message.info.lineBackground": rgba(p["accent_bg"], 0.10),
        "testing.coverCountBadgeBackground": p["accent_bg"],
        "testing.coverCountBadgeForeground": p["accent_fg"],
        "testing.coveredBackground": rgba(p["success_bg"], 0.25),
        "testing.coveredBorder": p["success_bg"],
        "testing.uncoveredBackground": rgba(p["error_bg"], 0.25),
        "testing.uncoveredBorder": p["error_bg"],
        # --- 聊天 / 智能体 ---
        "chat.requestBubbleBackground": p["bg_card"],
        "chat.requestBubbleHoverBackground": p["bg_hover_card"],
        "chat.avatarBackground": p["accent_bg"],
        "chat.avatarForeground": p["accent_fg"],
        "chat.slashCommandBackground": rgba(p["accent_bg"], 0.15),
        "chat.slashCommandForeground": p["accent_standalone"],
        "chat.editedFileForeground": p["warning_standalone"],
        "chat.linesAddedForeground": p["success_standalone"],
        "chat.linesRemovedForeground": p["error_standalone"],
        "chat.inputWorkingBorderColor1": p["accent_bg"],
        "chat.thinkingShimmer": p["fg_dim"],
        "chat.checkpointSeparator": p["border_dim"],
        "agents.background": p["bg_window"],
        "agentsPanel.background": p["bg_sidebar"],
        "agentsPanel.foreground": p["fg_sidebar"],
        "agentsPanel.border": p["border"],
        "agentsCard.border": p["border"],
        "agentsBottomPanel.border": p["border"],
        "agentsChatInput.background": p["bg_input"],
        "agentsChatInput.foreground": p["fg_view"],
        "agentsChatInput.border": p["border_input"],
        "agentsChatInput.focusBorder": rgba(p["accent_bg"], 0.75),
        "agentsChatInput.placeholderForeground": p["fg_placeholder"],
        "agentsNewSessionButton.background": "#00000000",
        "agentsNewSessionButton.foreground": p["fg"],
        "agentsNewSessionButton.border": p["border_input"],
        "agentsNewSessionButton.hoverBackground": p["bg_hover"],
        "agentsBadge.background": p["accent_bg"],
        "agentsBadge.foreground": p["accent_fg"],
        "agentsUnreadBadge.background": p["accent_bg"],
        "agentsUnreadBadge.foreground": p["accent_fg"],
        "agentStatusIndicator.background": p["accent_bg"],
        "agentsGradient.tintColor": p["accent_bg"],
        # --- 通知 ---
        "notifications.background": p["bg_popover"],
        "notifications.foreground": p["fg_popover"],
        "notifications.border": p["border"],
        "notificationsErrorIcon.foreground": p["error_standalone"],
        "notificationsWarningIcon.foreground": p["warning_standalone"],
        "notificationsInfoIcon.foreground": p["accent_standalone"],
        "notificationCenter.border": p["border"],
        "notificationCenterHeader.background": p["bg_headerbar"],
        "notificationCenterHeader.foreground": p["fg_headerbar"],
        "notificationLink.foreground": p["accent_standalone"],
        # --- 预览 / 评论 / 其他 ---
        "peekView.border": p["accent_bg"],
        "peekViewEditor.background": p["bg_card"],
        "peekViewEditorGutter.background": p["bg_card"],
        "peekViewEditor.matchHighlightBackground": p["find_match"],
        "peekViewEditor.matchHighlightBorder": "#00000000",
        "peekViewResult.background": p["bg_popover"],
        "peekViewResult.fileForeground": p["fg_popover"],
        "peekViewResult.lineForeground": p["fg_dim_popover"],
        "peekViewResult.matchHighlightBackground": rgba(p["accent_bg"], 0.25),
        "peekViewResult.selectionBackground": rgba(p["accent_bg"], 0.3),
        "peekViewResult.selectionForeground": p["fg_popover"],
        "peekViewTitle.background": p["bg_headerbar"],
        "peekViewTitleDescription.foreground": p["fg_dim_headerbar"],
        "peekViewTitleLabel.foreground": p["fg_headerbar"],
        "editor.snippetTabstopHighlightBackground": rgba(p["accent_bg"], 0.2),
        "editor.snippetTabstopHighlightBorder": p["border_input"],
        "editor.snippetFinalTabstopHighlightBackground": rgba(p["success_bg"], 0.2),
        "editor.snippetFinalTabstopHighlightBorder": p["success_bg"],
        "symbolIcon.arrayForeground": sy("def:identifier", fallback=p["fg"]),
        "symbolIcon.booleanForeground": sy("def:boolean", fallback=p["fg"]),
        "symbolIcon.classForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.colorForeground": hue("red", 2, 4),
        "symbolIcon.constantForeground": sy("def:constant", fallback=p["fg"]),
        "symbolIcon.constructorForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.enumeratorForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.enumeratorMemberForeground": sy("def:constant", fallback=p["fg"]),
        "symbolIcon.eventForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.fieldForeground": sy("def:identifier", fallback=p["fg"]),
        "symbolIcon.fileForeground": p["fg_dim"],
        "symbolIcon.folderForeground": p["fg_dim"],
        "symbolIcon.functionForeground": sy("def:statement", fallback=p["fg"]),
        "symbolIcon.interfaceForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.keyForeground": sy("def:constant", fallback=p["fg"]),
        "symbolIcon.keywordForeground": sy("def:statement", fallback=p["fg"]),
        "symbolIcon.methodForeground": sy("def:statement", fallback=p["fg"]),
        "symbolIcon.moduleForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.namespaceForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.nullForeground": sy("def:constant", fallback=p["fg"]),
        "symbolIcon.numberForeground": sy("def:number", fallback=p["fg"]),
        "symbolIcon.objectForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.operatorForeground": sy("def:statement", fallback=p["fg"]),
        "symbolIcon.packageForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.propertyForeground": sy("def:identifier", fallback=p["fg"]),
        "symbolIcon.referenceForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.snippetForeground": sy("def:string", fallback=p["fg"]),
        "symbolIcon.stringForeground": sy("def:string", fallback=p["fg"]),
        "symbolIcon.structForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.textForeground": p["fg_dim"],
        "symbolIcon.typeParameterForeground": sy("def:type", fallback=p["fg"]),
        "symbolIcon.unitForeground": sy("def:number", fallback=p["fg"]),
        "symbolIcon.variableForeground": sy("def:identifier", fallback=p["fg"]),
        "charts.foreground": p["fg"],
        "charts.lines": p["border"],
        "charts.red": hue("red", 1, 4),
        "charts.blue": hue("blue", 1, 4),
        "charts.yellow": hue("yellow", 4, 5),
        "charts.orange": hue("orange", 1, 4),
        "charts.green": hue("green", 1, 5),
        "charts.purple": hue("purple", 1, 4),
        # --- 欢迎页 / 引导页 ---
        "welcomePage.background": p["bg_window"],
        "welcomePage.progress.background": p["accent_bg"],
        "welcomePage.progress.foreground": p["accent_fg"],
        "welcomePage.tileBackground": p["bg_card"],
        "welcomePage.tileHoverBackground": p["bg_hover_card"],
        "welcomePage.tileBorder": p["border"],
        "walkThrough.embeddedEditorBackground": p["bg_window"],
        # --- 补齐其余内置主题键 ---
        "actionBar.toggledBackground": p["bg_active_view"],
        "browser.border": "#00000000",
        "commandCenter.background": p["bg_button_headerbar"],
        "commandCenter.border": "#00000000",
        "commandCenter.foreground": p["fg_headerbar"],
        "commandCenter.activeBackground": p["bg_active_headerbar"],
        "commandCenter.activeBorder": p["border_input"],
        "commandCenter.activeForeground": p["fg_headerbar"],
        "editorSuggestWidget.focusOutline": rgba(p["accent_bg"], 0.75),
        "list.invalidItemForeground": p["error_standalone"],
        "minimap.background": p["editor_bg"],
        "minimap.selectionHighlight": p["selection"],
        "minimap.selectionOccurrenceHighlight": p["word_highlight"],
        "minimap.findMatchHighlight": p["find_match"],
        "minimap.errorHighlight": p["error_standalone"],
        "minimap.warningHighlight": p["warning_standalone"],
        "minimapGutter.addedBackground": p["success_standalone"],
        "minimapGutter.modifiedBackground": p["accent_standalone"],
        "minimapGutter.deletedBackground": p["error_standalone"],
        "minimapSlider.background": p["scrollbar"],
        "minimapSlider.hoverBackground": p["scrollbar_hover"],
        "minimapSlider.activeBackground": p["scrollbar_active"],
        "modernActivityBar.border": p["sidebar_border"],
        "modernActivityBarItem.activeBackground": p["bg_active_sidebar"],
        "modernActivityBarItem.activeForeground": p["fg_sidebar"],
        "modernActivityBarItem.hoverBackground": p["bg_hover_sidebar"],
        "modernActivityBarItem.hoverForeground": p["fg_sidebar"],
        "notificationToast.border": p["border"],
        "panelInput.border": p["border_input"],
        "panelStickyScroll.shadow": "#00000000",
        "quickInputList.focusHighlightForeground": p["accent_standalone"],
        "scrollbar.shadow": "#00000000",
        "scrollbarSlider.background": p["scrollbar"],
        "scrollbarSlider.hoverBackground": p["scrollbar_hover"],
        "scrollbarSlider.activeBackground": p["scrollbar_active"],
        "searchEditor.textInputBorder": p["border_input"],
        "settings.dropdownBackground": p["bg_popover"],
        "settings.dropdownBorder": p["border_input"],
        "settings.headerForeground": p["fg_dim"],
        "settings.modifiedItemIndicator": p["accent_bg"],
        "settings.numberInputBorder": p["border_input"],
        "settings.textInputBorder": p["border_input"],
        "sideBarStickyScroll.shadow": "#00000000",
        "statusBar.focusBorder": "#00000000",
        "statusBar.inactiveBackground": p["bg_headerbar_backdrop"],
        "statusBarItem.compactHoverBackground": p["bg_hover_headerbar"],
        "statusBarItem.focusBorder": rgba(p["accent_bg"], 0.75),
        "statusBarItem.prominentHoverForeground": p["fg_headerbar"],
        "surface.background": p["bg_window"],
        "surface.border": p["border"],
        "surface.foreground": p["fg"],
        "textPreformat.background": p["bg_hover_view"],
        "toolbar.activeBackground": p["bg_active"],
        "toolbar.hoverBackground": p["bg_hover"],
        # --- 行内编辑 ---
        "inlineEdit.originalBackground": p["diff_removed_bg"],
        "inlineEdit.originalBorder": p["error_bg"],
        "inlineEdit.originalChangedLineBackground": rgba(p["error_bg"], 0.25),
        "inlineEdit.originalChangedTextBackground": rgba(p["error_bg"], 0.4),
        "inlineEdit.modifiedBackground": p["diff_inserted_bg"],
        "inlineEdit.modifiedBorder": p["success_bg"],
        "inlineEdit.modifiedChangedLineBackground": rgba(p["success_bg"], 0.25),
        "inlineEdit.modifiedChangedTextBackground": rgba(p["success_bg"], 0.4),
        "inlineEdit.tabWillAcceptOriginalBorder": p["accent_bg"],
        "inlineEdit.tabWillAcceptModifiedBorder": p["accent_bg"],
        "inlineEdit.gutterIndicator.background": p["bg_hover_view"],
        "inlineEdit.gutterIndicator.primaryBackground": rgba(p["accent_bg"], 0.25),
        "inlineEdit.gutterIndicator.primaryBorder": p["accent_bg"],
        "inlineEdit.gutterIndicator.primaryForeground": p["accent_fg"],
        "inlineEdit.gutterIndicator.secondaryBackground": p["bg_hover_view"],
        "inlineEdit.gutterIndicator.secondaryBorder": p["border"],
        "inlineEdit.gutterIndicator.secondaryForeground": p["fg_dim_view"],
        "inlineEdit.gutterIndicator.successfulBackground": rgba(p["success_bg"], 0.25),
        "inlineEdit.gutterIndicator.successfulBorder": p["success_bg"],
        "inlineEdit.gutterIndicator.successfulForeground": p["success_fg"],
        # --- 终端符号图标 ---
        "terminalSymbolIcon.aliasForeground": sy("def:statement", fallback=p["fg"]),
        "terminalSymbolIcon.argumentForeground": sy("def:identifier", fallback=p["fg"]),
        "terminalSymbolIcon.branchForeground": sy("def:type", fallback=p["fg"]),
        "terminalSymbolIcon.commitForeground": p["fg_dim_view"],
        "terminalSymbolIcon.fileForeground": p["fg_dim_view"],
        "terminalSymbolIcon.flagForeground": sy("def:identifier", fallback=p["fg"]),
        "terminalSymbolIcon.folderForeground": p["fg_dim_view"],
        "terminalSymbolIcon.inlineSuggestionForeground": p["fg_disabled_view"],
        "terminalSymbolIcon.methodForeground": sy("def:statement", fallback=p["fg"]),
        "terminalSymbolIcon.optionForeground": sy("def:identifier", fallback=p["fg"]),
        "terminalSymbolIcon.optionValueForeground": sy("def:constant", fallback=p["fg"]),
        "terminalSymbolIcon.pullRequestForeground": p["success_standalone"],
        "terminalSymbolIcon.pullRequestDoneForeground": hue("purple", 1, 4),
        "terminalSymbolIcon.remoteForeground": p["accent_standalone"],
        "terminalSymbolIcon.stashForeground": p["fg_dim_view"],
        "terminalSymbolIcon.symbolText": p["fg_dim_view"],
        "terminalSymbolIcon.symbolicLinkFileForeground": p["accent_standalone"],
        "terminalSymbolIcon.symbolicLinkFolderForeground": p["accent_standalone"],
        "terminalSymbolIcon.tagForeground": sy("def:constant", fallback=p["fg"]),
        # --- 仪表 ---
        "gauge.background": p["bg_hover_view"],
        "gauge.foreground": p["accent_bg"],
        "gauge.border": p["border_input"],
        "gauge.errorBackground": rgba(p["error_bg"], 0.25),
        "gauge.errorForeground": p["error_bg"],
        "gauge.warningBackground": rgba(p["warning_bg"], 0.25),
        "gauge.warningForeground": p["warning_bg"],
        # --- 源代码管理图表 ---
        "scmGraph.foreground1": hue("blue", 2, 4),
        "scmGraph.foreground2": hue("orange", 2, 4),
        "scmGraph.foreground3": hue("green", 2, 5),
        "scmGraph.foreground4": hue("purple", 1, 4),
        "scmGraph.foreground5": hue("teal", 2, 5),
        "scmGraph.historyItemRefColor": p["accent_standalone"],
        "scmGraph.historyItemRemoteRefColor": hue("purple", 1, 4),
        "scmGraph.historyItemBaseRefColor": p["warning_standalone"],
        "scmGraph.historyItemHoverDefaultLabelBackground": p["bg_headerbar"],
        "scmGraph.historyItemHoverDefaultLabelForeground": p["fg_headerbar"],
        "scmGraph.historyItemHoverLabelForeground": p["fg_popover"],
        "scmGraph.historyItemHoverAdditionsForeground": p["success_standalone"],
        "scmGraph.historyItemHoverDeletionsForeground": p["error_standalone"],
        # --- 现代 UI ---
        "modernUI.shellBackground": p["bg_window"],
        "modernUI.inactiveShellBackground": p["bg_headerbar_backdrop"],
        "modernTab.activeBackground": p.over(p["fg"], 0.10, "bg_headerbar"),
        "modernTab.activeForeground": p["fg_headerbar"],
        "modernTab.hoverBackground": p["bg_hover_headerbar"],
        "modernTab.hoverForeground": p["fg_headerbar"],
        "modernEditorTab.activeBackground": p.over(p["fg"], 0.10, "bg_headerbar"),
        "modernEditorTab.activeForeground": p["fg_headerbar"],
        "modernEditorTab.activeHoverBackground": p.over(p["fg"], 0.13, "bg_headerbar"),
        "modernEditorTab.inactiveBackground": p["bg_headerbar"],
        "modernEditorTab.hoverBackground": p["bg_hover_headerbar"],
        "modernEditorTab.hoverForeground": p["fg_headerbar"],
        "modernEditorTab.activeActionBackground": p["bg_active_headerbar"],
        "modernEditorTab.activeHoverActionBackground": p.over(p["fg"], 0.16, "bg_headerbar"),
        "modernEditorTab.hoverActionBackground": p["bg_hover_headerbar"],
        "modernEditorTab.selectedActionBackground": p["bg_active_headerbar"],
        # --- 括号对参考线 ---
        "editorBracketPairGuide.background1": rgba(hue("blue", 2, 4), 0.35),
        "editorBracketPairGuide.background2": rgba(hue("orange", 2, 4), 0.35),
        "editorBracketPairGuide.background3": rgba(hue("purple", 1, 4), 0.35),
        "editorBracketPairGuide.background4": rgba(hue("green", 2, 5), 0.35),
        "editorBracketPairGuide.background5": rgba(hue("pink", 2, 5), 0.35),
        "editorBracketPairGuide.background6": rgba(hue("teal", 2, 5), 0.35),
        "editorBracketPairGuide.activeBackground1": hue("blue", 2, 4),
        "editorBracketPairGuide.activeBackground2": hue("orange", 2, 4),
        "editorBracketPairGuide.activeBackground3": hue("purple", 1, 4),
        "editorBracketPairGuide.activeBackground4": hue("green", 2, 5),
        "editorBracketPairGuide.activeBackground5": hue("pink", 2, 5),
        "editorBracketPairGuide.activeBackground6": hue("teal", 2, 5),
        # --- 概览标尺 ---
        "editorOverviewRuler.background": "#00000000",
        "editorOverviewRuler.commentForeground": p["success_standalone"],
        "editorOverviewRuler.commentUnresolvedForeground": p["accent_standalone"],
        "editorOverviewRuler.commentDraftForeground": p["warning_standalone"],
        "editorOverviewRuler.commonContentForeground": p["fg_dim"],
        "editorOverviewRuler.currentContentForeground": p["success_standalone"],
        "editorOverviewRuler.incomingContentForeground": p["accent_standalone"],
        "editorOverviewRuler.inlineChatInserted": p["success_standalone"],
        "editorOverviewRuler.inlineChatRemoved": p["error_standalone"],
        "editorOverviewRuler.rangeHighlightForeground": p["find_match"],
        "editorOverviewRuler.wordHighlightTextForeground": p["word_highlight"],
        # --- 设置编辑器 ---
        "settings.checkboxBackground": p["bg_input"],
        "settings.checkboxBorder": p["border_input"],
        "settings.checkboxForeground": p["fg_view"],
        "settings.dropdownForeground": p["fg_popover"],
        "settings.dropdownListBorder": p["border"],
        "settings.focusedRowBackground": rgba(p["accent_bg"], 0.12),
        "settings.focusedRowBorder": p["accent_bg"],
        "settings.headerBorder": p["border_dim"],
        "settings.sashBorder": p["border_dim"],
        "settings.numberInputBackground": p["bg_input"],
        "settings.numberInputForeground": p["fg_view"],
        "settings.textInputBackground": p["bg_input"],
        "settings.textInputForeground": p["fg_view"],
        "settings.rowHoverBackground": p["bg_hover"],
        "settings.settingsHeaderHoverForeground": p["fg"],
        # --- 测试 ---
        "testing.coveredGutterBackground": rgba(p["success_bg"], 0.4),
        "testing.uncoveredGutterBackground": rgba(p["error_bg"], 0.4),
        "testing.uncoveredBranchBackground": rgba(p["error_bg"], 0.25),
        "testing.message.error.badgeBackground": p["error_bg"],
        "testing.message.error.badgeBorder": p["error_bg"],
        "testing.message.error.badgeForeground": p["error_fg"],
        "testing.messagePeekBorder": p["error_bg"],
        "testing.messagePeekHeaderBackground": p["error_bg"],
        "testing.iconPassed.retired": p["fg_disabled"],
        "testing.iconFailed.retired": p["fg_disabled"],
        "testing.iconErrored.retired": p["fg_disabled"],
        "testing.iconQueued.retired": p["fg_disabled"],
        "testing.iconUnset.retired": p["fg_disabled"],
        "testing.iconSkipped.retired": p["fg_disabled"],
        # --- 列表 --------------------------------------------------------------
        "list.dropBetweenBackground": rgba(p["accent_bg"], 0.75),
        "list.filterMatchBackground": rgba(p["accent_bg"], 0.25),
        "list.filterMatchBorder": p["accent_bg"],
        "list.inactiveFocusBackground": p["bg_active_sidebar"],
        "list.inactiveFocusOutline": p["border_dim"],
        # --- 缩略图 ---
        "minimap.chatEditHighlight": rgba(p["accent_bg"], 0.4),
        "minimap.foregroundOpacity": "#000000c0",
        "minimap.infoHighlight": p["accent_standalone"],
        # --- Notebook ---
        "notebook.cellEditorBackground": p["editor_bg"],
        "notebook.focusedCellBackground": rgba(p["accent_bg"], 0.08),
        "notebook.inactiveFocusedCellBorder": p["border_input"],
        "notebook.symbolHighlightBackground": rgba(p["accent_bg"], 0.15),
        # --- 聊天 -----------------------------------------------------------------
        "chat.requestBackground": p["bg_window"],
        "chat.requestBorder": p["border"],
        "chat.requestCodeBorder": p["border_input"],
        # --- 差异 ------------------------------------------------------------------
        "diffEditor.insertedTextBorder": p["success_bg"],
        "diffEditor.removedTextBorder": p["error_bg"],
        "diffEditor.move.border": p["warning_bg"],
        "diffEditor.moveActive.border": p["warning_standalone"],
        # --- 扩展图标 ---
        "extensionIcon.preReleaseForeground": p["warning_standalone"],
        "extensionIcon.privateForeground": p["error_standalone"],
        "extensionIcon.sponsorForeground": hue("pink", 2, 4),
        "extensionIcon.starForeground": p["warning_standalone"],
        "extensionIcon.verifiedForeground": p["accent_standalone"],
        # --- Markdown 提示块 ---
        "markdownAlert.note.foreground": p["accent_standalone"],
        "markdownAlert.tip.foreground": p["success_standalone"],
        "markdownAlert.important.foreground": hue("purple", 1, 4),
        "markdownAlert.warning.foreground": p["warning_standalone"],
        "markdownAlert.caution.foreground": p["error_standalone"],
        # --- 光标 / 操作列表 / 评论 ---
        "editorMultiCursor.primary.background": p["editor_cursor"],
        "editorMultiCursor.primary.foreground": p["editor_bg"],
        "editorMultiCursor.secondary.background": p["accent_standalone"],
        "editorMultiCursor.secondary.foreground": p["editor_bg"],
        "editorActionList.background": p["bg_popover"],
        "editorActionList.foreground": p["fg_popover"],
        "editorActionList.focusBackground": p.over(p["accent_bg"], 0.25, "bg_popover"),
        "editorActionList.focusForeground": p["fg_popover"],
        "commentsView.resolvedIcon": p["success_standalone"],
        "commentsView.unresolvedIcon": p["accent_standalone"],
        # --- 交互窗口 / 终端 ---
        "interactive.activeCodeBorder": p["accent_bg"],
        "interactive.inactiveCodeBorder": p["border"],
        "terminal.findMatchBorder": p["accent_bg"],
        "terminal.findMatchHighlightBorder": p["border_input"],
        "terminal.initialHintForeground": p["fg_disabled_view"],
        # --- 智能体会话窗口 ---
        "agentsUpdateButton.downloadingBackground": p["accent_bg"],
        "agentsUpdateButton.downloadedBackground": p["success_bg"],
        "agentsMobileDiff.addedForeground": p["success_standalone"],
        "agentsMobileDiff.deletedForeground": p["error_standalone"],
        "agentsMobileDiff.modifiedForeground": p["warning_standalone"],
        "activeSessionView.background": p["bg_card"],
        "activeSessionView.foreground": p["fg_card"],
        "inactiveSessionView.background": p["bg_window"],
        "inactiveSessionView.foreground": p["fg_dim"],
        "agentFeedbackEditorWidget.background": p["bg_popover"],
        "agentFeedbackEditorWidget.border": p["border"],
        # --- 图表 ---
        "chart.axis": p["border"],
        "chart.guide": p["border_dim"],
        "chart.line": p["accent_standalone"],
        # --- 命令中心 / 复选框 / 徽章 ---
        "commandCenter.debuggingBackground": p["warning_bg"],
        "commandCenter.inactiveBorder": p["border_dim"],
        "commandCenter.inactiveForeground": p["fg_dim_headerbar"],
        "checkbox.disabled.background": p["bg_input_disabled"],
        "checkbox.disabled.foreground": p["fg_disabled_view"],
        "panelTitleBadge.background": p["accent_bg"],
        "panelTitleBadge.foreground": p["accent_fg"],
        "searchEditor.findMatchBackground": p["find_match"],
        "searchEditor.findMatchBorder": p["accent_bg"],
        # --- 缩进参考线 / 装订线 / 合并 ---
        "editorIndentGuide.background2": p["indent_guide"],
        "editorIndentGuide.background3": p["indent_guide"],
        "editorIndentGuide.background4": p["indent_guide"],
        "editorIndentGuide.background5": p["indent_guide"],
        "editorIndentGuide.background6": p["indent_guide"],
        "editorIndentGuide.activeBackground2": p["indent_guide_active"],
        "editorIndentGuide.activeBackground3": p["indent_guide_active"],
        "editorIndentGuide.activeBackground4": p["indent_guide_active"],
        "editorIndentGuide.activeBackground5": p["indent_guide_active"],
        "editorIndentGuide.activeBackground6": p["indent_guide_active"],
        "editorGutter.commentGlyphForeground": p["success_standalone"],
        "editorGutter.commentUnresolvedGlyphForeground": p["accent_standalone"],
        "editorGutter.commentDraftGlyphForeground": p["warning_standalone"],
        "editorGutter.itemBackground": p["bg_hover_view"],
        "editorGutter.itemGlyphForeground": p["fg_dim_view"],
        "merge.border": p["border"],
        "merge.commonContentBackground": rgba(p["fg_dim"], 0.25),
        "merge.commonHeaderBackground": rgba(p["fg_dim"], 0.4),
        "merge.currentContentBackground": rgba(p["success_bg"], 0.25),
        "merge.currentHeaderBackground": rgba(p["success_bg"], 0.4),
        "merge.incomingContentBackground": rgba(p["accent_bg"], 0.25),
        "merge.incomingHeaderBackground": rgba(p["accent_bg"], 0.4),
        # --- 最后一轮：补齐注册表全部键 ---
        "agentFeedbackInputWidget.border": p["border_input"],
        "agentSessionReadIndicator.foreground": p["accent_standalone"],
        "agentSessionSelectedBadge.border": p["accent_bg"],
        "agentSessionSelectedUnfocusedBadge.border": p["border_input"],
        "aiCustomizationManagement.sashBorder": p["border_dim"],
        "chatManagement.sashBorder": p["border_dim"],
        "debugIcon.stepBackForeground": p["accent_standalone"],
        "debugTokenExpression.type": sy("def:type", fallback=p["fg"]),
        "editor.border": p["border_dim"],
        "editor.compositionBorder": p["accent_bg"],
        "editor.findMatchBorder": p["accent_bg"],
        "editor.findMatchHighlightBorder": p["border_input"],
        "editor.findMatchHighlightForeground": p["editor_search_match_fg"],
        "editor.findRangeHighlightBorder": "#00000000",
        "editor.focusedStackFrameHighlightBackground": rgba(p["success_bg"], 0.25),
        "editor.foldBackground": rgba(p["accent_bg"], 0.15),
        "editor.foldPlaceholderForeground": p["fg_dim_view"],
        "editor.inactiveLineHighlightBackground": rgba(p["fg_view"], 0.04),
        "editor.inlineValuesBackground": rgba(p["accent_bg"], 0.15),
        "editor.inlineValuesForeground": p["fg_dim_view"],
        "editor.linkedEditingBackground": rgba(p["accent_bg"], 0.2),
        "editor.placeholder.foreground": p["fg_placeholder"],
        "editor.selectionForeground": p["editor_fg"],
        "editor.stackFrameHighlightBackground": rgba(p["warning_bg"], 0.25),
        "editor.symbolHighlightBackground": rgba(p["accent_bg"], 0.2),
        "editor.symbolHighlightBorder": p["accent_bg"],
        "editor.wordHighlightBorder": "#00000000",
        "editor.wordHighlightStrongBorder": "#00000000",
        "editor.wordHighlightTextBorder": "#00000000",
        "editorBracketMatch.foreground": p["fg_view"],
        "editorError.border": p["error_bg"],
        "editorWarning.border": p["warning_bg"],
        "editorInfo.border": p["accent_bg"],
        "editorGhostText.border": "#00000000",
        "editorGroup.dropIntoPromptBorder": p["border_input"],
        "editorMarkerNavigationError.headerBackground": p["error_bg"],
        "editorMarkerNavigationWarning.headerBackground": p["warning_bg"],
        "editorMarkerNavigationInfo.headerBackground": p["accent_bg"],
        "editorMinimap.inlineChatInserted": p["success_standalone"],
        "editorStickyScrollGutter.background": p["bg_card"],
        "editorUnnecessaryCode.opacity": "#000000c0",
        "mcpIcon.starForeground": p["warning_standalone"],
        "mergeEditor.conflictingLines.background": rgba(p["warning_bg"], 0.2),
        "modernActivityBar.background": p["bg_sidebar"],
        "modernActivityBar.inactiveBackground": p["bg_sidebar_backdrop"],
        "modernPanel.border": p["border"],
        "modernSash.gripForeground": p["fg_disabled"],
        "notebookEditorOverviewRuler.runningCellForeground": p["accent_standalone"],
        "notebookScrollbarSlider.background": p["scrollbar"],
        "notebookScrollbarSlider.hoverBackground": p["scrollbar_hover"],
        "notebookScrollbarSlider.activeBackground": p["scrollbar_active"],
        "notebookStatusErrorIcon.foreground": p["error_standalone"],
        "notebookStatusRunningIcon.foreground": p["accent_standalone"],
        "notebookStatusSuccessIcon.foreground": p["success_standalone"],
        "outputView.background": p["bg_window"],
        "outputViewStickyScroll.background": p["bg_card"],
        "peekViewEditorStickyScroll.background": p["bg_card"],
        "peekViewEditorStickyScrollGutter.background": p["bg_card"],
        "profiles.sashBorder": p["border_dim"],
        "scrollbar.background": "#00000000",
        "search.resultsInfoForeground": p["fg_dim_view"],
        "sideBarStickyScroll.background": p["bg_card"],
        "sideBarStickyScroll.border": p["border"],
        "sideBarTitle.background": p["bg_sidebar"],
        "sideBarTitle.border": p["border"] if p.high_contrast else "#00000000",
        "sideBySideEditor.horizontalBorder": p["border_dim"],
        "sideBySideEditor.verticalBorder": p["border_dim"],
        "simpleFindWidget.sashBorder": p["border_dim"],
        "tab.unfocusedInactiveModifiedBorder": p["border_dim"],
        "terminalCommandGuide.foreground": p["border_input"],
        "terminalOverviewRuler.border": "#00000000",
        "terminalOverviewRuler.cursorForeground": p["accent_standalone"],
        "terminalOverviewRuler.findMatchForeground": p["find_match"],
        "terminalStickyScroll.background": p["bg_card"],
        "terminalStickyScroll.border": p["border"],
        "terminalStickyScrollHover.background": p["bg_hover_card"],
        "textPreformat.border": p["border_input"],
        "toolbar.hoverOutline": p["border_input"],
        "walkthrough.stepTitle.foreground": p["fg"],
    }

    if colorful_status_bar:
        colors.update(
            {
                "statusBar.background": p["accent_bg"],
                "statusBar.foreground": p["accent_fg"],
                "statusBarItem.hoverBackground": p["accent_hover"],
                "statusBarItem.activeBackground": p["accent_active"],
                "statusBarItem.prominentBackground": p["accent_hover"],
                "statusBarItem.prominentForeground": p["accent_fg"],
                "statusBarItem.prominentHoverBackground": p["accent_active"],
                "statusBar.debuggingBackground": p["warning_bg"],
                "statusBar.debuggingForeground": p["warning_fg"],
                "statusBar.noFolderBackground": p["accent_active"],
                "statusBar.noFolderForeground": p["accent_fg"],
                "statusBarItem.remoteBackground": p["success_bg"],
                "statusBarItem.remoteForeground": p["success_fg"],
            }
        )

    return {key: value for key, value in colors.items() if value is not None}
